version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-apache-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7.21
        environment:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: cc_test

    working_directory: ~/repo

    steps:
      #checkout repository
      - checkout

      #copy local config, this is somehow needed for selenium tests
      - run: sudo cp /home/circleci/repo/.circleci/config_local.php /home/circleci/repo/

      #install php extensions needed
      - run: sudo apt install -y libpng-dev
      - run: sudo docker-php-ext-install gd
        #needed for imap install
      - run: sudo apt install -y libc-client-dev libkrb5-dev
      - run: sudo docker-php-ext-configure imap --with-kerberos --with-imap-ssl
      - run: sudo docker-php-ext-install imap
      - run: sudo apt install -y mysql-client
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo docker-php-ext-enable pdo_mysql

      #config apache
      - run: sudo chmod 777 /etc/apache2/sites-enabled
      - run: sudo cp /home/circleci/repo/.circleci/example.conf /etc/apache2/sites-available/eoo.conf
      - run: sudo a2ensite eoo
      - run: sudo service apache2 restart

      #selenium
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.141.59.jar -log stdout
          Xvfb: 7055
          background: true

      - run:
          name: Download and start X
          command: |
            sudo apt-get install -y x11vnc
            x11vnc -forever -nopw
          background: true

      #install composer dependecies
      - run: composer update

      #make tests/logs/forbiddenlog.txt unwritable
      - run: sudo chmod 444 tests/logs/forbiddenlog.txt

        #open config_local.php and write the $_ENV vars there
        #only this way selenium has them available too
      - run:
          name: Get Email credentials to config
          command: |
            sudo chmod 777 config_local.php
            echo "\define('STD_EMAIL',           '$TEST_STD_EMAIL');" >> config_local.php
            echo "\define('STD_EMAIL_NAME',      '$TEST_STD_EMAIL_NAME');" >> config_local.php
            echo "\define('EMAIL_HOST',          '$TEST_EMAIL_HOST');" >> config_local.php
            echo "\define('EMAIL_PORT',          '$TEST_EMAIL_PORT');" >> config_local.php
            echo "\define('EMAIL_USERNAME',      '$TEST_EMAIL_USERNAME');" >> config_local.php
            echo "\define('EMAIL_PASSWORD',      '$TEST_EMAIL_PASSWORD');" >> config_local.php
            echo "\define('IMAP_PATH_SENT_MAIL', '$TEST_IMAP_PATH_SENT_MAIL');" >> config_local.php


      #run tests
      - run:
          name: Run Unit tests
          command: |
            vendor/bin/phpunit --coverage-clover=coverage.xml
            bash <(curl -s https://codecov.io/bash)


workflows:
  version: 2
  build-and-test:
    jobs:
      - build